name: Uber Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: balogsun/uber-clone

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push uber clone image
#        working-directory: src/adservice
        run: |
          docker build -t balogsen/uber:latest .
          docker push balogsen/uber:latest
          docker rmi balogsen/uber:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ca-central-1 --name pjct-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f K8s/deployment.yml
          kubectl apply -f K8s/service.yml
